### ISSUE TITLE
Build should generate image based on `version` script, not always `-dev`

### ISSUE THREAD

**Issue by yasker** [rancher/pipeline#11]
It should not be always
```
rancher/jenkins-boot:dev
rancher/jenkins-slave:dev
rancher/pipeline:dev
rancher/pipeline-ui:dev
```

`script/version` can automatically detect the git commit or tag in order to be used in the generated image.

**Comment by deniseschannon** [comment]
@biblesyme You will need to update this line: 

https://github.com/rancher/pipeline/blob/master/scripts/package#L16 to fix the scripts.

**Comment by gitlawr** [comment]
updated the generated tag

**Comment by deniseschannon** [comment]
Verified it's working with the latest.
