### ISSUE TITLE
show "no permissions" while adding repository in using private Gitlab server

### ISSUE THREAD

**Issue by OOChaosKnightOO** [rancher/pipeline#32]
Rancher : v1.6.13
Rancher-Pipeline : v0.1.1
Gitlab : Community Edition 8.0.4

After Configuring Source Code Management Authentication, I started to "add Pipeline" in the page. I choosed one of the repositories which were created by the User with "Master" Branch, then I got:
1) `"no permissions" ` warning message appears below
2)  cannot activate `"Webhook"`
3)  when I attempted to save the pipeline, the message` {"error":"Invalid url given"}` popped up on the top right corner.

**Comment by gitlawr** [comment]
1. What is your gitlab account permission level for the selected repository? The account can only manage webhook when it has `admin` level so we will disable `webhook` option when it is not.
2. Is the gitlab external url set properly, say, can you do a git pull from according repository link?

**Comment by OOChaosKnightOO** [comment]
Thanks a lot,
After changing the account permission level to `admin` , Everything goes fine.
The problem has been solved.
