### ISSUE TITLE
pipeline ui https访问的问题

### ISSUE THREAD

**Issue by xiongmingwu** [rancher/pipeline#36]
本人在https环境部署了rancher pipeline页面一直提示如下图所示：
![image](https://user-images.githubusercontent.com/31282628/37564035-d0d82a40-2ac8-11e8-81c2-b6f8cba2f6bd.png)
打开调试面板发现部分页面请求了http地址，如下图：
![image](https://user-images.githubusercontent.com/31282628/37564016-8b771a24-2ac8-11e8-9d4e-07b0d2fc812c.png)
修改nginx配置如下,也未能解决该问题：
server {
	listen 80;
	server_name xxx.xxx.com
	return 301 https://$server_name$request_uri;
}
能否修复该问题？

**Comment by xiongmingwu** [comment]
该问题已有人反馈，请参考：https://github.com/rancher/pipeline-ui/issues/3

**Comment by biblesyme** [comment]
Please follow the issue in rancher/rancher#13401
