### ISSUE TITLE
gitlab 11.1.1-ce  "API V3 is no longer supported. Use API V4 instead" 

### ISSUE THREAD

**Issue by xiaogangfighting** [rancher/pipeline#48]
![image](https://user-images.githubusercontent.com/5702303/44141136-cdf10f66-a0ae-11e8-8cda-5ee4430ff14b.png)
GitLab 11.1.1-ce /rancher1.6.17

**Comment by zi6me** [comment]
Got similar problem.

The code using API v3 is here
https://github.com/rancher/pipeline/blob/master/scm/gitlab_manager.go
//use v3 endpoint for compatibility 
 const gitlabAPI = "%s%s/api/v3" 

Need change it to v4

And also following https://docs.gitlab.com/ee/api/v3_to_v4.html  to check all API used and change it if neccessary
