### ISSUE TITLE
is rancher pipeline support gerrit

### ISSUE THREAD

**Issue by xiexianbin** [rancher/pipeline#63]
rancher pipeline is support `GitHub` `GitLab` and `Bitbucket`，is it support `gerrit` for pipeline

**Comment by gitlawr** [comment]
Please open issues for Rancher2.0 pipeline in the `rancher/rancher` repo with `area/pipeline` label.
`gerrit` is not supported at the moment, you can file a feature request issue for it and we can investigate according to the demand.
